"""USDA Cropland Data Layer class codes.

CDL encodes land cover as a single byte per pixel. The mapping is published as
a static legend and does not change between annual releases, so it is checked
in rather than fetched -- the pipeline should not depend on a network call to
label its own output.

Codes 1-80 and 195+ are agricultural. Codes 81-143 and 152-195 come from NLCD
and describe non-agricultural cover (water, forest, developed, wetland).
"""

CDL_CLASSES: dict[int, str] = {
    0: "Background",
    1: "Corn",
    2: "Cotton",
    3: "Rice",
    4: "Sorghum",
    5: "Soybeans",
    6: "Sunflower",
    10: "Peanuts",
    11: "Tobacco",
    12: "Sweet Corn",
    13: "Popcorn or Ornamental Corn",
    14: "Mint",
    21: "Barley",
    22: "Durum Wheat",
    23: "Spring Wheat",
    24: "Winter Wheat",
    25: "Other Small Grains",
    26: "Winter Wheat / Soybeans (double crop)",
    27: "Rye",
    28: "Oats",
    29: "Millet",
    30: "Speltz",
    31: "Canola",
    32: "Flaxseed",
    33: "Safflower",
    34: "Rape Seed",
    35: "Mustard",
    36: "Alfalfa",
    37: "Other Hay / Non-Alfalfa",
    38: "Camelina",
    39: "Buckwheat",
    41: "Sugarbeets",
    42: "Dry Beans",
    43: "Potatoes",
    44: "Other Crops",
    45: "Sugarcane",
    46: "Sweet Potatoes",
    47: "Miscellaneous Vegetables & Fruits",
    48: "Watermelons",
    49: "Onions",
    50: "Cucumbers",
    51: "Chick Peas",
    52: "Lentils",
    53: "Peas",
    54: "Tomatoes",
    55: "Caneberries",
    56: "Hops",
    57: "Herbs",
    58: "Clover / Wildflowers",
    59: "Sod / Grass Seed",
    60: "Switchgrass",
    61: "Fallow / Idle Cropland",
    63: "Forest",
    64: "Shrubland",
    65: "Barren",
    66: "Cherries",
    67: "Peaches",
    68: "Apples",
    69: "Grapes",
    70: "Christmas Trees",
    71: "Other Tree Crops",
    72: "Citrus",
    74: "Pecans",
    75: "Almonds",
    76: "Walnuts",
    77: "Pears",
    81: "Clouds / No Data",
    82: "Developed",
    83: "Water",
    87: "Wetlands",
    88: "Non-Agricultural / Undefined",
    92: "Aquaculture",
    111: "Open Water",
    112: "Perennial Ice / Snow",
    121: "Developed / Open Space",
    122: "Developed / Low Intensity",
    123: "Developed / Medium Intensity",
    124: "Developed / High Intensity",
    131: "Barren",
    141: "Deciduous Forest",
    142: "Evergreen Forest",
    143: "Mixed Forest",
    152: "Shrubland",
    176: "Grassland / Pasture",
    190: "Woody Wetlands",
    195: "Herbaceous Wetlands",
    204: "Pistachios",
    205: "Triticale",
    206: "Carrots",
    207: "Asparagus",
    208: "Garlic",
    209: "Cantaloupes",
    210: "Prunes",
    211: "Olives",
    212: "Oranges",
    213: "Honeydew Melons",
    214: "Broccoli",
    215: "Avocados",
    216: "Peppers",
    217: "Pomegranates",
    218: "Nectarines",
    219: "Greens",
    220: "Plums",
    221: "Strawberries",
    222: "Squash",
    223: "Apricots",
    224: "Vetch",
    225: "Winter Wheat / Corn (double crop)",
    226: "Oats / Corn (double crop)",
    227: "Lettuce",
    228: "Triticale / Corn (double crop)",
    229: "Pumpkins",
    230: "Lettuce / Durum Wheat (double crop)",
    231: "Lettuce / Cantaloupe (double crop)",
    232: "Lettuce / Cotton (double crop)",
    233: "Lettuce / Barley (double crop)",
    234: "Durum Wheat / Sorghum (double crop)",
    235: "Barley / Sorghum (double crop)",
    236: "Winter Wheat / Sorghum (double crop)",
    237: "Barley / Corn (double crop)",
    238: "Winter Wheat / Cotton (double crop)",
    239: "Soybeans / Cotton (double crop)",
    240: "Soybeans / Oats (double crop)",
    241: "Corn / Soybeans (double crop)",
    242: "Blueberries",
    243: "Cabbage",
    244: "Cauliflower",
    245: "Celeriac",
    246: "Radishes",
    247: "Turnips",
    248: "Eggplants",
    249: "Gourds",
    250: "Cranberries",
    254: "Barley / Soybeans (double crop)",
}

# Non-agricultural codes, drawn from NLCD rather than the crop survey. Split
# out because "63% of this soil unit is farmed" is a different statement from
# "63% of it is covered by something", and the demo needs the former.
NON_AGRICULTURAL = frozenset(
    {0, 63, 64, 65, 81, 82, 83, 87, 88, 111, 112, 121, 122, 123, 124, 131, 141, 142, 143, 152, 176, 190, 195}
)


def class_name(code: int) -> str:
    return CDL_CLASSES.get(code, f"Unknown ({code})")


def is_agricultural(code: int) -> bool:
    return code not in NON_AGRICULTURAL and code in CDL_CLASSES
